### ISSUE TITLE
最新版菜单管理的相关Bug

### ISSUE THREAD

**Issue by tlerbao** [JaguarJack/catch-admin-vue#21]
问题一：编辑菜单时，保存会让本来正确的权限标识变成错误的。上次说过了：https://bbs.catchadmin.com/topic/122

问题二：最新版的，按钮权限菜单名称和权限标识全部是Select固定死的了，列表中不存在的完全没办法新增，需要改进；比如我要是新增下图的按钮权限，在最新版完全没办法。
![image](https://user-images.githubusercontent.com/20442232/134364766-2e43d7b9-cdda-4122-8934-f94c81e1a9a1.png)

**Comment by JaguarJack** [comment]
第一个无法复现
第二个是正常的，Select 是支持 create 的，要是不支持，怎么会出现 select 限定之外的呢？

**Comment by tlerbao** [comment]
> 第一个无法复现
> 第二个是正常的，Select 是支持 create 的，要是不支持，怎么会出现 select 限定之外的呢？

第二个测试确实可以输入了，但第一个，你随便找一个菜单 非按钮什么也不该直接保存，就会出现问题了。 原本是 xxx@index 形式的，因为那行代码，把本来@之前的包括@都截断了，导致本来存到数据库已经正确的值xxx@index 变成了index 

在编辑的时候。不是新增。不给你发证人你是不信啊，宝贝

![image](https://user-images.githubusercontent.com/20442232/134790742-a4f93818-0d02-4a24-ae8e-1504b67d4907.png)

**Comment by JaguarJack** [comment]
菜单的里面有没有 `@` 符号没有影响。建议是不加，写个 `Controller` 名称就行了
