### ISSUE TITLE
前端运行不起来

### ISSUE THREAD

**Issue by Kepserver** [JaguarJack/catch-admin-vue#26]
catch-admin@4.4.0 dev
> vue-cli-service serve

'vue-cli-service' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by Kepserver** [comment]
> 
yarn config set registry https://registry.npm.taobao.org/
git clone https://github.com/yanwenwu/catch-admin-vue.git
cd到目录
yarn install
npm run dev
就报错

**Comment by tlerbao** [comment]
用npm install

**Comment by chanbigbig** [comment]
> 用npm install

成功解决
